name: check

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/cachix/install-nix-action@v27
      - run: nix flake check .