name: check

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo jq
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/cachix/install-nix-action@v27
      - name: Show flake info
        run: nix flake metadata && nix flake show
      # Re-enable when https://github.com/NixOS/nix/issues/8621 is resolved
      # - name: Check flake configuration
      #   run: nix flake check